# SPDX-FileCopyrightText: 2026 Vulis Project Contributors
# SPDX-License-Identifier: LicenseRef-Vulis-BSL-1.1

import logging

import pytest
from pydantic import ValidationError

from vulis_core import (
    VulisSettings,
    bind_context,
    get_correlation_id,
    get_logger,
    get_settings,
    init_logging,
    set_correlation_id,
)


@pytest.fixture(autouse=True)
def reset_logging_state():
    # Ensure each test starts from a known state.

    init_logging(force=True, service="test", level="DEBUG", fmt="console")
    set_correlation_id(None)
    yield
    # Clean up for the next test.
    init_logging(force=True, service="test", level="DEBUG", fmt="console")
    set_correlation_id(None)


def test_get_logger_returns_bound_logger() -> None:
    log = get_logger("test.module")
    # structlog bound loggers expose .info / .debug / etc.
    assert hasattr(log, "info")
    assert hasattr(log, "error")


def test_logger_emits_without_raising(capfd: pytest.CaptureFixture[str]) -> None:
    log = get_logger("test")
    log.info("hello", what="world")
    out = capfd.readouterr().out
    assert "hello" in out
    assert "world" in out


def test_service_name_is_stamped(capfd: pytest.CaptureFixture[str]) -> None:
    init_logging(service="my-svc", force=True, fmt="console")
    get_logger().info("ping")
    out = capfd.readouterr().out
    assert "my-svc" in out


def test_bind_context_appears_in_output(capfd: pytest.CaptureFixture[str]) -> None:
    with bind_context(project_id="proj_x", line_id="line_1"):
        get_logger().info("did-something")
    out = capfd.readouterr().out
    assert "proj_x" in out
    assert "line_1" in out


def test_bind_context_is_scoped(capfd: pytest.CaptureFixture[str]) -> None:
    with bind_context(project_id="inside"):
        pass
    # Outside the block, project_id should NOT leak.
    get_logger().info("after")
    out = capfd.readouterr().out
    assert "inside" not in out


def test_nested_bind_context_overrides_then_restores(
    capfd: pytest.CaptureFixture[str],
) -> None:
    with bind_context(project_id="outer"):
        with bind_context(line_id="inner"):
            get_logger().info("nested")
        out_inner = capfd.readouterr().out
    get_logger().info("after")
    out_after = capfd.readouterr().out

    assert "outer" in out_inner
    assert "inner" in out_inner
    # After the outer block exits, outer is gone too.
    assert "outer" not in out_after


def test_correlation_id_autogenerated() -> None:
    set_correlation_id(None)
    cid = get_correlation_id()
    assert cid
    assert isinstance(cid, str)
    # Reading again returns the same id.
    assert get_correlation_id() == cid


def test_correlation_id_is_overridable() -> None:
    set_correlation_id("req-123")
    assert get_correlation_id() == "req-123"


def test_correlation_id_appears_in_logs(
    capfd: pytest.CaptureFixture[str],
) -> None:
    set_correlation_id("trace-abc")
    get_logger().info("event")
    out = capfd.readouterr().out
    assert "trace-abc" in out


# ─── Settings ────────────────────────────────────────────────


def test_settings_defaults() -> None:
    get_settings.cache_clear()
    s = VulisSettings()
    assert s.surface in ("workstation", "server", "edge")
    assert s.environment in ("dev", "staging", "prod")
    assert s.log_level == "INFO"
    assert s.storage_backend == "local-fs"


def test_settings_env_prefix(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("VULIS_SERVICE_NAME", "dataset")
    monkeypatch.setenv("VULIS_LOG_LEVEL", "DEBUG")
    s = VulisSettings()
    assert s.service_name == "dataset"
    assert s.log_level == "DEBUG"


def test_settings_masked_dump_hides_secrets(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("VULIS_POSTGRES_DSN", "postgresql://u:secret@h/db")
    s = VulisSettings()
    dump = s.masked_dump()
    assert "secret" not in dump["postgres_dsn"]
    assert dump["postgres_dsn"] == "***"


def test_settings_masked_dump_shows_none() -> None:
    s = VulisSettings()
    dump = s.masked_dump()
    assert dump["postgres_dsn"] == "<none>"


def test_settings_validates_surface(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("VULIS_SURFACE", "moon")
    with pytest.raises(ValidationError):
        VulisSettings()


def test_logging_accepts_int_level() -> None:
    init_logging(level=logging.WARNING, force=True)


def test_logging_idempotent_without_force() -> None:
    # Calling again without force should be a no-op (no exception).
    init_logging(service="a", force=True)
    init_logging(service="b")  # ignored
