"""Auto-generated model card builder.

Renders a Markdown model card for a ``ModelVersion`` from a Jinja2
template embedded in this module (so the service has no filesystem
dependency on a templates directory at runtime).

The card includes:

* Model + version metadata
* ONNX specs (opset, IR version, input/output tensors with shape)
* Trained-on dataset version (if linked)
* Approval transition history (read from the audit trail)
* BSL-1.1 disclaimer footer
"""

# SPDX-FileCopyrightText: 2026 Vulis Project Contributors
# SPDX-License-Identifier: LicenseRef-Vulis-BSL-1.1

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from jinja2 import Template

from vulis_registry.models import ModelStatus, ModelVersion, OnnxTensorSpec

CARD_TEMPLATE = Template(
    """\
# {{ model.name }} — v{{ version_str }}

> {{ model.description or "No description provided." }}

| Field | Value |
|---|---|
| **Model ID** | `{{ model.id }}` |
| **Version ID** | `{{ version.id }}` |
| **Tenant** | `{{ version.tenant_id }}` |
| **Project** | `{{ model.project_id }}` |
| **Task kind** | `{{ model.task_kind }}` |
| **Status** | `{{ version.status.value }}` |
| **Created by** | `{{ version.created_by }}` |
| **Created at** | `{{ version.created_at.isoformat() }}` |
| **Artifact key** | `{{ version.artifact_key }}` |
| **Artifact digest (sha256)** | `{{ version.artifact_digest }}` |
| **Artifact size** | {{ version.artifact_size_bytes }} bytes |
| **ONNX opset** | `{{ version.onnx_opset }}` |
{%- if version.mlflow_run_id %}
| **MLflow run ID** | `{{ version.mlflow_run_id }}` |
{%- endif %}
{%- if version.trained_on_dataset_version_id %}
| **Trained on dataset version** | `{{ version.trained_on_dataset_version_id }}` |
{%- endif %}

## Inputs ({{ onnx.inputs | length }})

{% if onnx.inputs %}
| Name | DType | Shape |
|---|---|---|
{% for t in onnx.inputs %}
| `{{ t.name }}` | `{{ t.dtype }}` | `{{ t.shape }}` |
{% endfor %}
{% else %}
_None._
{% endif %}

## Outputs ({{ onnx.outputs | length }})

{% if onnx.outputs %}
| Name | DType | Shape |
|---|---|---|
{% for t in onnx.outputs %}
| `{{ t.name }}` | `{{ t.dtype }}` | `{{ t.shape }}` |
{% endfor %}
{% else %}
_None._
{% endif %}

{% if transitions %}
## Approval history

| When | Actor | Verb | From | To |
|---|---|---|---|---|
{% for tr in transitions %}
| `{{ tr.occurred_at }}` | `{{ tr.actor }}` | `{{ tr.verb }}` | `{{ tr.from_state }}` | `{{ tr.to_state }}` |
{% endfor %}
{% else %}
_No transitions recorded yet (still in DRAFT)._
{% endif %}

{% if version.metadata_ %}
## Metadata

```json
{{ metadata_json }}
```
{% endif %}

---

*Generated by vulis-registry. Licensed under BSL 1.1 — see `LICENSE` for details.*
"""
)


def _format_transitions(transition_rows: list[Any]) -> list[dict[str, Any]]:
    """Format audit_events rows for the card.

    Each row must expose ``action``, ``actor``, ``diff``, ``occurred_at``.
    We filter to ``model_version.promote`` actions.
    """
    out: list[dict[str, Any]] = []
    for row in transition_rows:
        if not row.action.startswith("model_version.promote"):
            continue
        diff: dict[str, Any] = {}
        if row.diff:
            try:
                diff = json.loads(row.diff)
            except (TypeError, ValueError):
                diff = {"raw": row.diff}
        out.append(
            {
                "actor": row.actor,
                "verb": diff.get("verb", "?"),
                "from_state": diff.get("from", "?"),
                "to_state": diff.get("to", "?"),
                "occurred_at": row.occurred_at.isoformat() if row.occurred_at else "?",
            }
        )
    return out


def build_model_card(
    *,
    model,
    version: ModelVersion,
    onnx_specs: list[OnnxTensorSpec],
    transition_rows: list[Any] | None = None,
) -> str:
    """Render a Markdown model card for ``version``.

    Parameters
    ----------
    model:
        The ``Model`` ORM instance (must be in the same tenant).
    version:
        The ``ModelVersion`` ORM instance.
    onnx_specs:
        The ``OnnxTensorSpec`` rows attached to the version.
    transition_rows:
        Optional list of audit_events rows (for the transition table).
    """
    inputs = [s for s in onnx_specs if s.direction == "input"]
    outputs = [s for s in onnx_specs if s.direction == "output"]
    onnx_view = {
        "inputs": [{"name": s.name, "dtype": s.dtype, "shape": list(s.shape)} for s in inputs],
        "outputs": [{"name": s.name, "dtype": s.dtype, "shape": list(s.shape)} for s in outputs],
    }
    transitions = _format_transitions(transition_rows or [])
    metadata_json = json.dumps(version.metadata_ or {}, indent=2, sort_keys=True, default=str)
    return CARD_TEMPLATE.render(
        model=model,
        version=version,
        version_str=f"{version.major}.{version.minor}.{version.patch}",
        onnx=onnx_view,
        transitions=transitions,
        metadata_json=metadata_json,
    )


__all__ = [
    "build_model_card",
]


# Suppress unused import warning for ModelStatus — referenced via the
# state machine but not directly here. Keeping the import makes the
# dependency explicit.
_ = ModelStatus
_ = datetime
